### Registrar ingreso de estudiante

POST http://localhost:8000/api/estudiantes
Content-Type: application/json

{
"cod": 5555,
  "nombres": "Carlos Perez",
  "email": "carlos@test.com"
}
###listar estudiantes

GET http://localhost:8000/api/estudiantes

### Agregar Notas

POST http://localhost:8000/api/notas
Content-Type: application/json

{
  "actividad": "Examen Final",
  "nota": 4.5,
  "codEstudiante": 5555
}