### Registrar ingreso de estudiante

POST http://localhost:8000/api/estudiantes
Content-Type: application/json

{
"cod": 5987,
  "nombres": "juan",
  "email": "juancho@test.com"
}
###listar estudiantes

GET http://localhost:8000/api/estudiantes

### Agregar Notas

POST http://localhost:8000/api/notas
Content-Type: application/json

{
  "actividad": "Examen Final",
  "nota": 2,
  "codEstudiante": 9876
}


### Buscar Estudiante por ID

GET http://localhost:8000/api/estudiantes/9876



### Actualizar Estudiante
PUT http://localhost:8000/api/estudiantes/5987
Content-Type: application/json

{
    "cod": "9267",
    "nombres": "Juan Pérez",
    "email": "juan.perez@example.com"
}

### Eliminar Estudiante
DELETE http://localhost:8000/api/estudiantes/5555
Content-Type: application/json





